name: Invoker
description: A Dependency-Injection container for mortals
version: 0.1.0
author: markupcode <andrew.devels@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  optional: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
